In [1]:
import numpy as np


In [5]:
arr=np.array([1,2,3,4,5,5])

In [6]:
print(arr)

[1 2 3 4 5 5]


In [7]:
print(arr[0]+arr[1])

3


In [9]:
arr=np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])

In [10]:
print(arr)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]


In [11]:
arr=np.array([[[1,2,3]],[[1,2,3]]])

In [12]:
print(arr)

[[[1 2 3]]

 [[1 2 3]]]


In [15]:
arr=np.array([[[1,2,3],[4,5,6],[7,89,9]],[[1,2,3],[2,3,4],[3,4,5]]])

In [16]:
print(arr)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7 89  9]]

 [[ 1  2  3]
  [ 2  3  4]
  [ 3  4  5]]]


In [17]:
print(arr[1:4])

[[[1 2 3]
  [2 3 4]
  [3 4 5]]]


In [25]:
print(arr.dtype)
print(arr.shape)

int32
(5,)


In [26]:
arr=np.array([1,2,3,4,5])
x=arr.copy()
arr[0]=32
print(arr)
print(x)

[32  2  3  4  5]
[1 2 3 4 5]


In [32]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])


In [33]:
newarr=arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [34]:
arr=np.array([1,2,3,4])
arr1=np.array([3,4,5,6])
arr2=arr+arr1
print(arr2)

[ 4  6  8 10]


In [40]:
arr2=np.concatenate((arr,arr1))


In [41]:
print(arr2)

[1 2 3 4 3 4 5 6]


In [42]:
arr2=np.stack((arr,arr1))
print(arr2)

[[1 2 3 4]
 [3 4 5 6]]


In [43]:
arr2=np.vstack((arr,arr1))
print(arr2)

[[1 2 3 4]
 [3 4 5 6]]


In [44]:
arr=np.array([1,2,3,4,5,6])
newarr=np.array_split(arr,3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [45]:
arr=np.array([1,23,4,5,6,7,7])
x=np.where(arr%2==0)
print(x)

(array([2, 4], dtype=int64),)


In [46]:
x=np.searchsorted(arr,[1,2,3])
print(x)

[0 1 1]


In [48]:
arr=np.array([41,42,43,44])
x=[True,False,True,False]
newarr=arr[x]
print(newarr)

[41 43]


In [58]:
arr=np.random.randint(102)
print(arr)

96


In [71]:
arr=np.random.choice([3,5,7,9],p=[0.1,0.3,0.6,0.0],size=[100])
print(arr)

[3 7 7 7 7 3 5 3 7 7 3 7 7 7 5 5 7 5 7 7 7 5 5 5 7 3 5 5 7 7 5 7 5 7 5 7 5
 7 7 7 7 7 5 5 5 5 7 5 5 7 5 3 5 5 7 5 3 7 7 7 7 7 7 7 7 5 5 7 7 7 7 7 5 7
 5 5 5 3 5 7 3 7 7 5 7 5 7 3 3 5 3 7 3 5 5 7 7 5 7 7]


In [64]:
arr=np.array([1,2,3,4,5])
x=np.random.shuffle(arr)
print(x)

None


In [65]:
arr=np.array([1,2,3,4,5])
x=np.random.permutation(arr)
print(x)

[4 2 3 5 1]


In [66]:
x=np.random.normal(size=(2,3))
print(x)

[[ 0.6430534   0.28269522  0.40880516]
 [ 0.44343819  1.76828182 -0.6432278 ]]


In [68]:
x=np.random.binomial(n=10,p=0.5,size=10)
print(x)


[5 6 4 5 8 4 5 2 3 8]


In [70]:
x=np.random.poisson(lam=2,size=10)
print(x)

[[0 1 0]
 [0 0 0]]


In [72]:
x=np.random.uniform(size=(2,3))
print(x)

[[0.97291159 0.98284537 0.47316855]
 [0.18523011 0.02544872 0.78697351]]


In [73]:
x=np.random.normal(loc=1,scale=2,size=(2,3))
print(x)

[[-2.26401413  0.23709604  0.92149349]
 [ 2.35536995  1.86087645 -0.4054086 ]]


In [75]:
x=np.random.multinomial(n=5,pvals=[1/5,1/5,1/5,1/5,1/5])
print(x)

[1 1 1 0 2]


In [76]:
x=np.random.exponential(scale=2,size=(2,3))
print(x)

[[1.09879581e+00 5.84678505e+00 3.97043890e+00]
 [2.93988528e-03 7.31363723e-01 5.36388529e+00]]


In [78]:
x=np.random.chisquare(df=2,size=(2,3))
print(x)

[[2.72381616 0.04698446 1.50098436]
 [0.12747054 4.23940922 0.09955609]]


In [81]:
num1=3
num=32
x=np.lcm(num1,num)
print(x)

96


In [82]:
num1=3
num=32
x=np.gcd(num1,num)
print(x)

1


In [86]:
x=np.sin(np.pi/2)
print(x)

1.0


In [87]:
x=np.sinh(np.pi/2)
print(x)

2.3012989023072947
